env:
  matrix:
  - ENV_FROM_APPLICATION_YML=true
  global:
    # This is HEROKU_API_KEY=<Denis' API key>
    secure: CMJUFGiw+vmXKySVyDztUwvJmE18yskWb8tQrW2GUsahRQwanb3UjaEtLC7AKw/tLGlUhgf5g7RdSxp0qis7qBnaNwGVwAWU+lQR4DC9X+qGnwZ7VnG9Z7Vsy7FoJYQhJJf01EF7D7s+Pdhu9U+N/ks6vAAIusodpFBbBa/4qDw=
branches:
  only:
    - develop
before_script:
- git describe
- mv config/database.yml.travis config/database.yml
- git config user.email "denis+camsys@constantorbit.com"
- git config user.name "Denis Haskin"
rvm:
- 1.9.3
bundler_args: --without development
script:
- bundle exec /usr/bin/env RAILS_ENV=test rake db:drop db:create db:reset
- bundle exec /usr/bin/env RAILS_ENV=test COVERALLS_NOISY=true rake oneclick:test_with_coveralls
notifications:
  email:
  - oneclickcs_github@googlegroups.com
  irc: irc.freenode.net#oneclick
deploy:
  provider: heroku
  api_key:
    secure: h4oO5/falwm1cIWu8SlGlJlWZese5B/ZIMaU2+e6kwhE/ekci2t9f/XeudpzHxLsBL5OAQiB9idZL2OCligYU8BexrrevzUcBwD4yg/OKVI/HK2VS/NON+fTWPf72tgFUF8cugZTN77X6ZtvapxICJs5y//1PcAG4VWc+z2feCk=
  app: oneclick-arc-int
  on:
    repo: camsys/oneclick
    branch: develop
after_deploy:
  - gem install heroku
  - git branch -lavv
  - git describe
  - heroku config:set ONECLICK_APP_VERSION=`git describe` --app oneclick-arc-int
