env:
  matrix:
  - ENV_FROM_APPLICATION_YML=true
  global:
    secure: jUJl8lJRBaROaPmLz64q20IvlN/eNwFjMcHRm4SgGMCcLf3eyIWqRsq5GQ9kKBL+QBfaSFdoEnaUN2/tq7dtu9zNOJNpMcHegY/nvQs3q3LIPCfG00GSAO/DBjLKQVVFOZzCjNuqesvWYPsBoAg8NHe1fUciZ67u0JMuLfitcWg=
branches:
  only:
  - develop
before_script:
- pwd
- ls -a
- mv config/database.yml.travis config/database.yml
- git config user.email "dedwards@camsys.com"
- git config user.name "Derek Edwards"
after_script:
- pwd
- ls -a
- git describe
rvm:
- 2.1.1
language: ruby
cache: bundler
bundler_args: "--without development"
script:
- bundle exec /usr/bin/env RAILS_ENV=test rake db:drop db:create db:reset
- bundle exec /usr/bin/env UI_MODE=desktop RAILS_ENV=test COVERALLS_NOISY=true rake oneclick:test_with_coveralls
notifications:
  slack:
    rooms:
    - camsys:lXMC55pg5oKxSTYW38zsB9jm#1click
deploy:
  provider: heroku
  api_key:
    secure: BnDSeczkLGQTaB6YHDmwsohRa71CPi6NdBSHo4X/d+st8gbyv2PcfE7qu0OSmrpOmxwYiqjQVcbp4JpjXhftM9IJok7qfFMv3VbQIOeCuvBYtVNhvDl+dI+i1Xn1lnrMzbZfPUsMlIPeQXe52jMzMYdeafcU4vHUEOg2HOGoQ3I=
  app: oneclick-arc-int
  on:
    repo: camsys/oneclick
    branch: develop
after_deploy:
 - heroku run rake db:migrate --app oneclick-arc-int
 - heroku run rake oneclick:load_locales --app oneclick-arc-int
